### ISSUE TITLE
顺丰打印接口的文档link失效了

### ISSUE THREAD

**Issue by YipingRuan** [ZhouShangLun/SfExpress#1]
方便简要说一下接受面单的API设计吗？

**Comment by ZhouShangLun** [comment]
https://qiao.sf-express.com/pages/developDoc/index.html?level2=265596
不好意思哈，是官网更新了文档地址，我很久没有关注了。
https://qiao.sf-express.com/pages/developDoc/index.html?level2=718833
分别看下这两个链接。
